<#
.SYNOPSIS
  Builds the distributable archive: a Data-rooted zip a mod manager can install.

.DESCRIPTION
  deploy-dev.ps1 puts the same two files into Vortex staging for testing. This
  makes the thing a stranger downloads, and the two must not drift.

  Chemistry is small on purpose -- it is policy, and everything it does it does
  by calling Rapport. Two files is the whole mod. What it is NOT is standalone:
  without Rapport installed, Autonomy.pex calls natives that do not exist and the
  script fails at runtime rather than at install, so the README says so and so
  does the mod page.

  ASCII only, deliberately -- see deploy-dev.ps1 for why.
#>
[CmdletBinding()]
param(
    [switch] $Force,[string] $OutDir = '')

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) { $OutDir = Join-Path $root 'build\release' }

# VERSION is the only place that declares one - read strictly, no fallback. The
# old way took the first "version x.y.z" in the README, fell back to a typed 0.1.0,
# and would have taken Rapport's number the day the README said "needs Rapport
# version 0.2.0".
$version = (Get-Content (Join-Path $root 'VERSION') -Raw).Trim()
if ($version -notmatch '^[0-9]+\.[0-9]+\.[0-9]+$') { throw "VERSION must hold a plain x.y.z, not '$version'" }
$existing = Join-Path $OutDir "Chemistry-$version.zip"
if ((Test-Path $existing) -and -not $Force) {
    throw "Chemistry-$version.zip already exists. Bump VERSION, or pass -Force to rebuild this exact version on purpose."
}

$stage = Join-Path $OutDir "Chemistry-$version"
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Force -Path $stage | Out-Null

$esp = Join-Path $root 'data\Chemistry.esp'
if (-not (Test-Path $esp)) { throw "MISSING: data\Chemistry.esp -- run tools/make_esp.py" }
Copy-Item $esp $stage -Force

$pex = Join-Path $root 'build\papyrus\Chemistry'
if (-not (Test-Path $pex)) { throw "MISSING: build\papyrus\Chemistry -- run scripts/build-papyrus.ps1" }
$scripts = Join-Path $stage 'Scripts\Chemistry'
New-Item -ItemType Directory -Force -Path $scripts | Out-Null
Copy-Item (Join-Path $pex '*.pex') $scripts -Force
# The staged copies only: no .pex in a stranger's download names this machine's
# folders, user or computer (dev-vs-release check, 2026-09-26). The game never reads
# those header fields.
& python (Join-Path $PSScriptRoot 'strip-pex.py') (Join-Path $stage 'Scripts') 'Chemistry'
if ($LASTEXITCODE -ne 0) { throw 'strip-pex.py failed - nothing packaged.' }

# The MCM menu (generated by scripts/build-mcm.py). MCM itself is optional.
$mcm = Join-Path $root 'data\MCM'
if (-not (Test-Path $mcm)) { throw "MISSING: data\MCM -- run scripts/build-mcm.py" }
Copy-Item $mcm $stage -Recurse -Force

foreach ($doc in 'LICENSE', 'README.md') {
    $p = Join-Path $root $doc
    if (Test-Path $p) { Copy-Item $p $stage -Force }
}

$zip = Join-Path $OutDir "Chemistry-$version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -CompressionLevel Optimal

Write-Host "Assembling Chemistry $version"
Write-Host ''
Write-Host 'Contents:'
Get-ChildItem $stage -Recurse -File |
    ForEach-Object { $_.FullName.Substring($stage.Length + 1) } |
    Sort-Object |
    ForEach-Object { Write-Host "    $_" }

$item = Get-Item $zip
Write-Host ''
Write-Host ("  {0}" -f $item.FullName)
Write-Host ("  {0:N0} bytes, {1} file(s)" -f $item.Length, @(Get-ChildItem $stage -Recurse -File).Count)
Write-Host ''
Write-Host 'Requires Rapport 0.2.1 or newer (API 201). Against an older Rapport it stays idle and says so once in Rapport.log.'
