<#
.SYNOPSIS
  Builds the distributable archive: a Data-rooted zip a mod manager can install.

.DESCRIPTION
  deploy-dev.ps1 puts the same two files into Vortex staging for testing. This
  makes the thing a stranger downloads, and the two must not drift.

  Chemistry is small on purpose -- it is policy, and everything it does it does
  by calling Rapport. Two files is the whole mod. What it is NOT is standalone:
  without Rapport installed, Autonomy.pex calls natives that do not exist and the
  script fails at runtime rather than at install, so the README says so and so
  does the mod page.

  ASCII only, deliberately -- see deploy-dev.ps1 for why.
#>
[CmdletBinding()]
param([string] $OutDir = '')

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) { $OutDir = Join-Path $root 'build\release' }

$version = '0.1.0'
$readme = Join-Path $root 'README.md'
if (Test-Path $readme) {
    $m = Select-String -Path $readme -Pattern 'version\s+([0-9]+\.[0-9]+\.[0-9]+)' |
         Select-Object -First 1
    if ($m) { $version = $m.Matches[0].Groups[1].Value }
}

$stage = Join-Path $OutDir "Chemistry-$version"
if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Force -Path $stage | Out-Null

$esp = Join-Path $root 'data\Chemistry.esp'
if (-not (Test-Path $esp)) { throw "MISSING: data\Chemistry.esp -- run tools/make_esp.py" }
Copy-Item $esp $stage -Force

$pex = Join-Path $root 'build\papyrus\Chemistry'
if (-not (Test-Path $pex)) { throw "MISSING: build\papyrus\Chemistry -- run scripts/build-papyrus.ps1" }
$scripts = Join-Path $stage 'Scripts\Chemistry'
New-Item -ItemType Directory -Force -Path $scripts | Out-Null
Copy-Item (Join-Path $pex '*.pex') $scripts -Force

# The MCM menu (generated by scripts/build-mcm.py). MCM itself is optional.
$mcm = Join-Path $root 'data\MCM'
if (-not (Test-Path $mcm)) { throw "MISSING: data\MCM -- run scripts/build-mcm.py" }
Copy-Item $mcm $stage -Recurse -Force

foreach ($doc in 'LICENSE', 'README.md') {
    $p = Join-Path $root $doc
    if (Test-Path $p) { Copy-Item $p $stage -Force }
}

$zip = Join-Path $OutDir "Chemistry-$version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -CompressionLevel Optimal

Write-Host "Assembling Chemistry $version"
Write-Host ''
Write-Host 'Contents:'
Get-ChildItem $stage -Recurse -File |
    ForEach-Object { $_.FullName.Substring($stage.Length + 1) } |
    Sort-Object |
    ForEach-Object { Write-Host "    $_" }

$item = Get-Item $zip
Write-Host ''
Write-Host ("  {0}" -f $item.FullName)
Write-Host ("  {0:N0} bytes, {1} file(s)" -f $item.Length, @(Get-ChildItem $stage -Recurse -File).Count)
Write-Host ''
Write-Host 'Requires Rapport. Without it this does nothing and errors in the Papyrus log.'
